version: '3'

networks:
  objective-php:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_laravel
    ports:
      - "7000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - objective-php

  mysql:
    image: mysql:5.7.29
    container_name: mysql_laravel
    restart: unless-stopped
    tty: true
    ports:
      - "9306:3306"
    environment:
      MYSQL_DATABASE: db_app
      MYSQL_USER: db_app
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - objective-php
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9004:9004"
    networks:
      - objective-php